server {
    listen 80;
    server_name apuri.pl www.apuri.pl _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        try_files /index.html =404;
    }

    location = /planner {
        return 301 https://planner.apuri.pl/;
    }

    location /planner/ {
        return 301 https://planner.apuri.pl/;
    }

    location = /stormbot {
        auth_basic "APURI Private Access";
        auth_basic_user_file /run/secrets/htpasswd;
        return 302 https://stormbot.apuri.pl/;
    }

    location /stormbot/ {
        auth_basic "APURI Private Access";
        auth_basic_user_file /run/secrets/htpasswd;
        return 302 https://stormbot.apuri.pl/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name planner.apuri.pl;

    auth_basic "APURI Private Access";
    auth_basic_user_file /run/secrets/htpasswd;

    root /usr/share/nginx/html/protected/planner;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name stormbot.apuri.pl;

    root /usr/share/nginx/html/protected/stormbot;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
